export default {
    fa:{
        index:{
            title:''
        },
        cart:{
            title:'سبد خرید',
            description:'',
            postinfo:'اطلاعات ارسال',
            paymentinfo:'اطلاعات پرداخت',
            entercoupon:'اگر کد تخفیف دارید وارد کنید',
            applydiscount:'اعمال تخفیف',
            applied:'اعمال شد',
            color:'رنگ',
            productid:'کد محصول',
            size:'سایز',
            onesize:'تک سایز',
            unitprice:'قیمت واحد',
            taxation:'مالیات',
            ordertotal:'جمع کل سفارش',
            discount:'تخفیف',
            productsinthecart:'تعداد کالا در سبد',
            pieces:'عدد',
            totalamountpayable:'مبلغ کل قابل پرداخت',
            nextstep:'ثبت و مرحله بعد',
            emptycart:'سبد خرید خالی است',
            recipientfullname:'نام و نام خانوادگی تحویل گیرنده',
            contactnumber:'شماره تماس (ضروری)',
            fixednumber:'شماره ثابت (اختیاری)',
            yourorderwillbesenttothefollowingaddressanddetails:'سفارش شما به آدرس و مشخصات زیر ارسال می‌شود',
            shippingcost:'هزینه ارسال',
            free:'رایگان',
            duetothecustomizedproductinyourshoppingcartyoucannot:'بدلیل وجود محصول سفارشی شده در سبد خریدتان امکان پرداخت درب منزل را ندارید',
            onlinepayment:'پرداخت آنلاین',
            doortodoorpayment:'پرداخت درب منزل',
            yourorderwillbeshippedatthefollowingtime:'سفارش شما در زمان زیر ارسال می‌شود',
            postagedate:'تاریخ و زمان ارسال',
            youwillnotbeabletopayatthedoor:'بدلیل وجود محصول سفارشی شده در سبد خریدتان امکان پرداخت درب منزل را ندارید',
            doesnotexistorhasexpired:'وجود ندارد یا منقضی شده',
            youarenotallowedtousethisgiftcard:'شما مجاز به استفاده از این گیفت کارت نیستید',
            tousethisdiscountcodeyoumustfirstlogin:'جهت استفاده از این کد تخفیف لازم است در ابتدا وارد شوید',
            pleasebepatient:'لطفا شکیبا باشید',
            transferringtothebankportal:'در حال انتقال به درگاه بانک',
            freedelivery:'ارسال رایگان',
            perudoor:'پرو درب منزل',
        },
        cartSuccess:{
            title:'عملیات موفق',
            description:'سفارش شما با موفقیت ثبت شد، جزئیات و فاکتور را در جدول زیر مشاهده کنید'
        },
        cartFaild:{
            title:'عملیات ناموفق',
            description:'خرید شما با خطا مواجه شد، دوباره امتحان کنید'
        },
        sex:{
            women:'زنانه',
            men:'مردانه',
            boy:'پسرانه',
            girl:'دخترانه',
            children:'کودکانه',
            unisexadult:'فارغ از جنسیت بزرگسالان',
            unisexchild:'فارغ از جنسیت کودکان',
        },
        comment:{
            send:'ثبت نظر',
            sendtextname1:'نظر شما با نام',
            sendtextname2:'ثبت میشود',
            textarea:'نظر خود را بنویسید',
            sendsuccess:'نظر شما پس از تایید مدیریت نمایش داده میشود',
            untitled:"بدون عنوان",
            dizasanswer:"پاسخ دیزا",
        },
        dashboard:{
            title:'داشبورد',
            wellcome:'خوش آمدید',
            profile:'پروفایل',
            wishlist:'لیست علاقه مندی ها',
            myorders:'سفارش های من',
            mygifts:'گیفت های من',
            referralrequest:'درخواست مرجوعی',
            notifications:'اطلاع رسانی ها',
            criticsandsuggestions:'انتقادات و پیشنهادات',
            recentvisits:'بازدید های اخیر',
            logout:'خروج از حساب کاربری',
            imsureofleaving:"از خروج مطمئنم",
            cancel:'انصراف',
            personalinformation:'اطلاعات شخصی',
            editinformation:'ویرایش اطلاعات',
            acceptandeditinformation:'تایید و ویرایش اطلاعات',
            email:'پست الکترونیک',
            postaladdress:'آدرس پستی',
            postalcode:'کد پستی',
            country:'کشور',
            state:'استان',
            city:'شهر',
            address:'آدرس',
            settings:'تنظیمات',
            emptynotice:'لیست اطلاع رسانی شما خالی میباشد',
            noticetype:'نوع اطلاع رسانی',
            inventory:'موجودی کالا',
            discount:'تخفیف کالا',
            productname:'نام کالا',
            brandname:'نام برند',
            active:'فعال',
            inactive:'غیرفعال',
            mygifts:'گیفت های من',
            mygiftsempty:'گیفت های منلیست گیفت شما خالی است',
            giftdetails:'جزئیات گیفت',
            finalamount:'مبلغ نهایی',
            orderdate:'تاریخ سفارش',
            referralcode:'کد پیگیری',
            amount:'قیمت',
            count:'تعداد',
            product:'محصول',
            customized:'سفارشی شده',
            link:'لینک',
            couponcode:'کد تخفیف',
            physical:'فیزیکی',
            digital:'دیجیتال',
            gifttype:'نوع گیفت',
            repayment:'پرداخت مجدد',
            successful:'پرداخت موفق',
            faild:'شکست خورده',
            downloadinvoice:'دانلود فاکتور',
            myordersempty:'لیست سفارش شما خالی است',
            orderdetails:'جزئیات سفارش',
            payathome:'پرداخت در محل',
            returnedpayathome:'پرداخت در محل (عودت شده)',
            grievance:{
                title:'درخواست برای ارجاع کالا',
                empty:'خوشبختانه تاکنون کالایی را مرجوع نکرده اید',
                status:'وضعیت',
                eventdate:'تاریخ ثبت',
                notapproved:'تایید نشده',
                approved:'تایید شده',
                pending:'در دست بررسی',
                referralhistory:'تاریخچه ارجاع کالا',
                description:'توضیحات',
                order:'سفارش',
                ordercode:'کد سفارش',
                orderamount:'مبلغ سفارش',
                requestforreferral:'درخواست برای ارجاع کالا',
                reasons:'لطفا دلایل خود را برایمان بنویسید',
                error:'لازم است ابتدا سفارشی ثبت کنید',
                success:'درخواست شما با موفقیت ثبت شد، از شما متشکریم',
                submit:'ثبت درخواست',
            },
            suggestions:{
                comment:'کاربر گرامی، شما می توانید در راستا ارائه خدمت بهتر نظرات خود را به ما منتقل کنید',
                submit:'ثبت نظر',
                placeholder:'اینجا تایپ کنید',
                error:'لطفا پیام خود را درست وارد کنید',
                success:'نظر شما با موفقیت ثبت شد، از شما متشکریم',
            }
        },
        joinus:{
            title:'همکاری با ما',
            h1:'همکاری با دیزا',
            description:'مجموعه‌ی ما تلاش دارد پلی برای ارتباط ارزشها و هنر طراحی با مخاطب باشد.\nبرای معرفی و فروش محصولاتی که با خلاقیت و کیفیت در راستای ارزشهای مد پایدار توسط طراحانی هنرمند خلق شده‌اند. خواهشمندیم برای آشنایی بیشتر فرم مربوطه را تکمیل نمایید.',
            collaborationform:'فرم همکاری',
            designername:'نام طراح',
            brandname:'نام برند',
            mobilenumber:'شماره همراه',
            email:'ایمیل',
            experience:'سابقه فعالیت',
            underoneyear:'زیر یک سال',
            onetotwoyears:'یک تا دو سال',
            twotofiveyears:'دو تا پنج سال',
            morethanfiveyears:'بیشتر از پنج سال',
            workplace:'محل فعالیت',
            instagrampageaddress:'آدرس صفحه اینستاگرام',
            websiteaddress:'آدرس وبسایت',
            whichcategory:'تولیدات شما در کدام دسته قرار می‌گیرد؟',
            clothing:'پوشاک',
            accessory:'اکسسوری',
            bag:'کیف',
            shoes:'کفش',
            textarea:'لطفا توضیح مختصری راجع به برند خود بنویسید',
            success:'درخواستتان با موفقیت ثبت شد، منتظر تماسمان بمانید',
            send:'ثبت درخواست',
        },
        trustbox:['ارائه کالای با اصالت','پرو درب منزل','پشتیبانی ۲۴ ساعته','ارسال رایگان'],
        contactcomment:'کاربر گرامی، شما میتوانید با پرکردن فرم زیر نظرات و پیشنهادات خود را با ما به اشتراک بگذارید',
        contactsuccess:'پیام شما با موفقیت ثبت شد، از شما متشکریم',
        loginwithmobile:'ورود با تلفن همراه',
        securitycode:'کد امنیتی',
        _securitycode:'کد امنیتی (چهار رقمی)',
        logincomment:'اگر تا بحال ثبت نام نکرده اید بعنوان کاربر جدید وارد میشوید',
        loginsms1:'کد امنیتی به شماره ',
        loginsms2:' پیامک شد',
        resendsecuritycode:'ارسال مجدد کد امنیتی',
        changemobilenumber:'تغییر شماره همراه',
        moreseconds:'ثانیه دیگر',
        firstnameandlastname:'نام و نام خانوادگی',
        mobilenumber:'شماره همراه',
        phonenumber:'شماره تماس',
        writeyourmessage:'پیام خود را بنویسید',
        email:'ثبت و ارسال نظر',
        sendmessage:'ارسال پیام',
        captchahasexpired:'کپچا منقضی شده است',
        pleasemarkthecaptcha:'لطفا کپچا را علامت بزنید',
        pleaseenterallitems:'لطفا تمامی موارد را وارد کنید',
        loading:'در حال بارگذاری',
        processing:'در حال پردازش',
        result:'نتیحه',
        noproductsfound:'محصولی یافت نشد',
        unavailable:'ناموجود',
        gender:'جنسبت',
        onlydiscountproducts:'فقط محصولات تخفیف دار',
        pricerange:'محدوده قیمت',
        userarea:'ناحیه کاربری',
        loginsignup:'ورود / ثبت نام',
        notifymewhenavailable:'موجود شد اطلاع بده',
        noticeofproductdiscounts:'اطلاع از تخفیف کالا',
        favorites:'علاقه مندی ها',
        search:'جستجو',
        dosearch:'جستجو کنید',
        home:'صفحه نخست',
        designers:'طراحان',
        about:'درباره',
        aboutdiza:'درباره دیــزا',
        products:'محصولات',
        special:'ویژه',
        giftcard:'گیفت کارت',
        gift:{
            thegiftcarddoesnotbelongtoyou:'گیفت کارت مذکور متعلق به شما نمی‌باشد',
            todisplaythecodeyoumustfirstauthenticate:'جهت نمایش کد بایستی ابتدا اهراز حویت کنید',
            digitalversion:'نسخه دیجیتالی',
            physicalversion:'نسخه فیزیکی',
            digitalversioncomment:'این نسخه رو می‌تونید به صورت لینک برای شخص مورد نظرتون ارسال کنید',
            physicalversioncomment:'این نسخه با کیفیت بالا چاپ و با انتخاب شما به آدرس فرستنده یا گیرنده ارسال میشه',
            buygiftcard:'خرید کارت هدیه',
            selecttheversionyouwant:'نسخه مورد نظر خود را انتخاب کنید',
            choiceoccasion:'انتخاب مناسبت',
            specifications:'مشخصات',
            thepayment:'پرداخت',
            completecontentofthecard:'محتوای کارت را تکمیل کنید',
            writeyourmessage:'پیام خود را بنویسید (حداکثر ۴۰ کلمه)',
            theamountpayable:'مبلغ قابل پرداخت',
            shippingtime:'زمان ارسال',
            address:'آدرس',
            mobilenumber:'شماره همراه',
            cardtype:'نوع کارت',
            recipientsname:'نام گیرنده',
            cardamount:'مبلغ کارت',
            printed:'چاپی',
            digital:'دیجیتال',
            orderspecifications:'مشخصات سفارش',
            attentioncomment:'پس از خرید، گیرنده باید شماره خود را جهت تایید و مسائل امنیتی وارد کند، لذا توجه داشته باشید که آن را به درستی وارد کرده‌اید',
            attention:'توجه',
            firstnameandlastname:'نام و نام خانوادگی',
            receiverspecifications:'مشخصات گیرنده',
            completeaddress:'آدرس کامل',
            iammyownreceiver:'گیرنده خودم هستم',
        },
        notify:{
            coupontext:'تخفیف های اختصاصی این کالا، به شماره موبایل شما اطلاع‌رسانی خواهد شد',
            inventorytext:'در صورت موجودی مجدد کالا، به شماره موبایل شما اطلاع‌رسانی خواهد شد',
        },
        realized:'متوجه شدم',
        completeyourstyle:'استایلت رو کامل کن',
        howtocare:'نحوه مراقبت',
        productdescription:'توضیحات محصول',
        productdetails:'جزئیات محصول',
        unavailablecomment:'این کالا در حال حاضر موجود نیست',
        productsizes:'سایز های محصول',
        size:'سایز',
        sizespecifications:'مشخصات سایز',
        othercolors:'رنگ های دیگر',
        sewingorder:'سفارش دوخت',
        custommade:'سفارشی',
        notavailable:'این محصول موجود نمی‌باشد',
        addtocart:'افزودن به سبد خرید',
        letmeknow:'موجود شد خبرم کن',
        producseo1:'قیمت و خرید آنلاین ',
        producseo2:' با طراحی ',
        producseo3:'',
        designer:'طراح',
        brand:'برند',
        transferringtothebank:'در حال انتقال به درگاه بانک',
        faildpurchase:'خرید ناموفق',
        successpurchase:'خرید موفق',
        successpurchasetext1:'خرید شما با موفقیت انجام شد و روز',
        successpurchasetext2:'برای شما ارسال می‌شود',
        successpurchasetext3:'خرید شما با موفقیت انجام شد، حالا می‌توانید لینک کارت هدیه را برای شخص مورد نظر ارسال کنید.',
        backtomainpage:'بازگشت به صفحه اصلی',
        previousstep:'مرحله قبل',
        nextstep:'مرحله بعد',
        receivingdata:'در حال دریافت اطلاعات',
        copylink:'کپی لینک',
        copycode:'کپی کد',
        other:'سایر',
        all:'همه',
        searchfor:'جستجو برای',
        orderby:'مرتب سازی بر اساس',
        sortByHit:'محبوب ترین',
        sortByNewest:'جدیدترین',
        sortByValuable:'بیشترین قیمت',
        sortByCutrate:'کمترین قیمت',
        latest:'جدید‌‌ترین',
        expensive:'قیمتی ترین',
        economical:'اقتصادی ترین',
        popular:'محبوب ترین',
        filter:'فیلتر',
        filterby:'فیلتر بر اساس',
        applyfilters:'اعمال فیلتر ها',
        applypricefilter:'اعمال فیلتر قیمت',
        from:'از',
        upto:'تا',
        minutesstudy:'دقیقه مطالعه',
        visits:'بازدید',
        video:'ویدیو',
        article:'مقاله',
        podcast:'پادکست',
        discounted:'تخفیف دار',
        seemore:'مشاهده بیشتر',
        dizadesigners:'طراحــان دیــزا',
        joindiza:'به دیزا بپیوندید',
        categories:'دسته بندی',
        _categories:'دسته ها',
        guest:'مهمان',
        recentvisits:'بازدید های اخیر',
        similarproducts:'محصولات مشابه',
        more:'بیشتر',
        fewer:'کمتر',
        back:'بازگشت',
        backtotop:'برگشت به بالا',
    },
    en:{
        index:{
            title:''
        },
        cart:{
            title:'Cart',
            description:'',
            postinfo:'post info',
            paymentinfo:'payment info',
            entercoupon:'enter if you have a discount code',
            applydiscount:'apply a discount',
            applied:'applied',
            color:'color',
            productid:'product id',
            size:'size',
            onesize:'one size',
            unitprice:'unit price',
            taxation:'tax',
            ordertotal:'order total',
            discount:'discount',
            productsinthecart:'products in the cart',
            pieces:'pieces',
            totalamountpayable:'total amount payable',
            nextstep:'next step',
            emptycart:'the cart is empty',
            recipientfullname:'Recipient fullname',
            contactnumber:'Contact number (required)',
            fixednumber:'Fixed number (optional)',
            yourorderwillbesenttothefollowingaddressanddetails:'your order will be sent to the following address and details',
            shippingcost:'shipping cost',
            free:'free',
            duetothecustomizedproductinyourshoppingcartyoucannot:'Due to the customized product in your shopping cart, you can not',
            onlinepayment:'online payment',
            doortodoorpayment:'door to door payment',
            yourorderwillbeshippedatthefollowingtime:'your order will be shipped at the following time',
            postagedate:'postage date',
            youwillnotbeabletopayatthedoor:'due to the presence of a customized product in your shopping cart, you will not be able to pay at the door',
            doesnotexistorhasexpired:'Does not exist or has expired',
            youarenotallowedtousethisgiftcard:'You are not allowed to use this gift card',
            tousethisdiscountcodeyoumustfirstlogin:'To use this discount code, you must first log in',
            pleasebepatient:'please be patient',
            transferringtothebankportal:'transferring to the bank portal',
            freedelivery:'free delivery',
            perudoor:'peru door',
        },
        cartSuccess:{
            title:'Successful operation',
            description:'your order has been successfully registered, see details and invoice in the table below'
        },
        cartFaild:{
            title:'Faild operation',
            description:'your purchase encountered an error, try again'
        },
        sex:{
            women:'women',
            men:'men',
            boy:'boys',
            girl:'girls',
            children:'children',
            unisexadult:'unisex adults',
            unisexchild:'unisex children'
        },
        comment:{
            send:'send comment',
            sendtextname1:'your comment will be registered under the name "',
            sendtextname2:'"',
            textarea:'Write your comment',
            sendsuccess:'your comment will be displayed after management approval',
            untitled:"untitled",
            dizasanswe0r:"diza's answer"
        },
        dashboard:{
            title:'dashboard',
            wellcome:'Wellcome',
            profile:'profile',
            wishlist:'wishlist',
            myorders:'my orders',
            mygifts:'my gifts',
            referralrequest:'referral request',
            notifications:'notices',
            criticsandsuggestions:'suggestions',
            recentvisits:'recent visits',
            logout:'logout',
            imsureofleaving:"I'm sure of leaving",
            cancel:'cancel',
            personalinformation:'personal information',
            editinformation:'edit information',
            acceptandeditinformation:'accept & edit information',
            email:'E-mail',
            postaladdress:'postal address',
            postalcode:'Postal code',
            country:'Country',
            state:'State',
            city:'City',
            address:'address',
            settings:'settings',
            emptynotice:'your notification list is empty',
            noticetype:'notice type',
            inventory:'inventory',
            discount:'discount',
            productname:'product name',
            brandname:'brand name',
            active:'active',
            inactive:'inactive',
            mygifts:'my gifts',
            mygiftsempty:'your gift list is empty',
            giftdetails:'gift details',
            finalamount:'final amount',
            orderdate:'order date',
            referralcode:'referral code',
            amount:'amount',
            count:'count',
            product:'product',
            customized:'customized',
            link:'link',
            couponcode:'coupon code',
            physical:'physical',
            digital:'digital',
            gifttype:'gift type',
            repayment:'repayment',
            successful:'successful',
            faild:'faild',
            downloadinvoice:'download invoice',
            myordersempty:'your order list is empty',
            orderdetails:'order details',
            payathome:'pay at home',
            returnedpayathome:'pay at home (returned)',
            grievance:{
                title:'referral request',
                empty:'Fortunately, you have not returned a product yet',
                status:'status',
                eventdate:'event date',
                notapproved:'not approved',
                approved:'approved',
                pending:'pending',
                referralhistory:'referral history',
                description:'description',
                order:'order',
                ordercode:'Order code',
                orderamount:'Order amount',
                requestforreferral:'request for referral',
                reasons:'please write your reasons for us',
                error:'you need to register a custom first',
                success:'your request has been successfully submitted, thank you',
                submit:'Submit a request',
            },
            suggestions:{
                comment:'dear user, you can send us your comments in order to provide a better service',
                submit:'Submit a comment',
                placeholder:'type here',
                error:'please enter your message correctly',
                success:'your comment was successfully submitted, thank you',
            }
        },
        joinus:{
            title:'join us',
            h1:'join diza',
            description:'our collection strives to be a bridge between values ​​and the art of design with the audience. \nTo introduce and sell products that have been created by artist designers with creativity and quality in line with sustainable fashion values. Please fill out the relevant form for more information.',
            collaborationform:'collaboration form',
            designername:'designer name',
            brandname:'brand name',
            mobilenumber:'mobile number',
            email:'email',
            experience:'experience',
            underoneyear:'Under one years',
            onetotwoyears:'One to two years',
            twotofiveyears:'Two to five years',
            morethanfiveyears:'More than five years',
            workplace:'work place',
            instagrampageaddress:'instagram address',
            websiteaddress:'website address',
            whichcategory:'in which category do your products fall?',
            clothing:'clothing',
            accessory:'accessory',
            bag:'bag',
            shoes:'shoes',
            textarea:'please write a brief description about your brand',
            success:'your request has been successfully submitted, please wait for our call',
            send:'submit a request',
        },
        trustbox:['products with originality','the art of iranian designers','24-hour support','fast sending'],
        contactcomment:'dear user, you can share your comments and suggestions with us by filling out the form below',
        contactsuccess:'your message was successfully registered, thank you',
        loginwithmobile:'login by mobile',
        securitycode:'security code',
        _securitycode:'Security code (four digits)',
        logincomment:'if you have not yet registered, you will be logged in as a new user',
        loginsms1:'the security code was texted to ',
        loginsms2:'',
        resendsecuritycode:'Re-send security code',
        changemobilenumber:'change mobile number',
        moreseconds:'more seconds',
        firstnameandlastname:'fullname',
        mobilenumber:'mobile number',
        phonenumber:'phone number',
        writeyourmessage:'write your message',
        email:'email',
        sendmessage:'send message',
        captchahasexpired:'captcha has expired',
        pleasemarkthecaptcha:'please mark the captcha',
        pleaseenterallitems:'please enter all items',
        loading:'loading',
        processing:'processing',
        result:'result',
        noproductsfound:'no products found',
        unavailable:'unavailable',
        gender:'sex',
        onlydiscountproducts:'only discount products',
        pricerange:'price range',
        userarea:'user area',
        loginsignup:'login / signup',
        notifymewhenavailable:'notify me when available',
        noticeofproductdiscounts:'notice of product discounts',
        favorites:'favorites',
        search:'Search',
        dosearch:'Search',
        special:'special',
        home:'home',
        designers:'designers',
        about:'about',
        aboutdiza:'about diza',
        products:'products',
        giftcard:'gift card',
        gift:{
            thegiftcarddoesnotbelongtoyou:'the gift card does not belong to you',
            todisplaythecodeyoumustfirstauthenticate:'to display the code, you must first authenticate',
            digitalversion:'digital version',
            physicalversion:'physicalversion',
            digitalversioncomment:'you can send this version as a link to the person you want',
            physicalversioncomment:'this version is printed in high quality and will be sent to the sender or recipient address of your choice',
            buygiftcard:'buy gift card',
            selecttheversionyouwant:'select the version you want',
            choiceoccasion:'choice occasion',
            specifications:'specifications',
            thepayment:'the payment',
            completecontentofthecard:'complete content of the card',
            writeyourmessage:'write your message (maximum 40 words)',
            theamountpayable:'the amount payable',
            shippingtime:'shipping time',
            address:'address',
            mobilenumber:'mobile number',
            cardtype:'card type',
            recipientsname:"recipient's name",
            cardamount:'card amount',
            printed:'printed',
            digital:'digital',
            orderspecifications:'order specifications',
            attentioncomment:'after the purchase, the recipient must enter their number for confirmation and security issues, so make sure you enter it correctly',
            attention:'attention',
            firstnameandlastname:'first name & last name',
            receiverspecifications:'receiver specifications',
            completeaddress:'complete address',
            iammyownreceiver:'i am my own receiver',
        },
        notify:{
            coupontext:'exclusive discounts on this product will be notified to your mobile number',
            inventorytext:'in case of re-inventory, your mobile number will be notified',
        },
        realized:'i realized',
        completeyourstyle:'complete your style',
        howtocare:'how to care',
        productdescription:'product description',
        productdetails:'product details',
        unavailablecomment:'this product is not available',
        productsizes:'product sizes',
        size:'size',
        sizespecifications:'size specifications',
        othercolors:'other colors',
        sewingorder:'sewing order',
        custommade:'custom made',
        notavailable:'not available',
        addtocart:'add to cart',
        letmeknow:'let me know',
        producseo1:'buy ',
        producseo2:' designed by ',
        producseo3:'',
        designer:'designer',
        brand:'brand',
        transferringtothebank:'transferring to the bank portal',
        faildpurchase:'unsuccessful purchase',
        successpurchase:'successful purchase',
        successpurchasetext1:'your purchase was successful and will be sent to you on',
        successpurchasetext2:'',
        successpurchasetext3:'your purchase was successful, now you can send the gift card link to the person.',
        copylink:'copy link',
        copycode:'copy code',
        backtomainpage:'back to main page',
        previousstep:'previous step',
        nextstep:'next step',
        receivingdata:'receiving data',
        other:'other',
        all:'all',
        searchfor:'search for',
        orderby:'order by',
        sortByHit:'most popular',
        sortByNewest:'the newest',
        sortByValuable:'highest price',
        sortByCutrate:'lowest price',
        latest:'The latest',
        expensive:'The most expensive',
        economical:'The most economical',
        popular:'The most popular',
        filter:'filter',
        filterby:'filter by',
        applyfilters:'apply filters',
        applypricefilter:'apply price filter',
        from:'from',
        upto:'up to',
        minutesstudy:'minutes study',
        visits:'visits',
        video:'video',
        article:'article',
        podcast:'podcast',
        discounted:'discounted',
        seemore:'see more',
        dizadesigners:'diza designers',
        joindiza:'join diza',
        categories:'categories',
        _categories:'categories',
        guest:'guest',
        recentvisits:'recent visits',
        similarproducts:'similar products',
        more:'more',
        fewer:'fewer',
        back:'back',
        backtotop:'back to top',
    },
    ar:{
        index:{
            title:''
        },
        cart:{
            title:'عربة التسوق',
            description:'',
            postinfo:'معلومات المشاركة',
            paymentinfo:'معلومات الدفع',
            entercoupon:'أدخل إذا كان لديك رمز الخصم',
            applydiscount:'تطبيق الخصم',
            applied:'مُطبَّق',
            color:'اللون',
            productid:'الرمز الشريطي',
            size:'بحجم',
            onesize:'حجم واحد',
            unitprice:'سعر الوحدة',
            taxation:'تحصيل الضرائب',
            ordertotal:'إجمالي الطلب الكلي',
            discount:'تخفيض',
            productsinthecart:'عدد البضائع في العربة',
            pieces:'حبات',
            totalamountpayable:'إجمالي المبلغ الواجب دفعه',
            nextstep:'التسجيل والخطوة التالية',
            emptycart:'عربة التسوق فارغة',
            recipientfullname:'اسم ولقب المستلم',
            contactnumber:'رقم الاتصال (مطلوب)',
            fixednumber:'رقم ثابت (اختياري)',
            yourorderwillbesenttothefollowingaddressanddetails:'سيتم إرسال طلبك إلى العنوان والتفاصيل التالية',
            shippingcost:'تكلفة الشحن',
            free:'حر',
            duetothecustomizedproductinyourshoppingcartyoucannot:'نظرًا للمنتج المخصص في عربة التسوق الخاصة بك ، لا يمكنك الدفع عند الباب',
            onlinepayment:'الدفع الالكتروني',
            doortodoorpayment:'الدفع من الباب الى الباب',
            yourorderwillbeshippedatthefollowingtime:'سيتم شحن طلبك في الوقت التالي',
            postagedate:'تاريخ ووقت التقديم',
            youwillnotbeabletopayatthedoor:'نظرًا لوجود منتج مخصص في عربة التسوق الخاصة بك ، فلن تتمكن من الدفع عند الباب',
            doesnotexistorhasexpired:'غير موجود أو انتهت صلاحيته',
            youarenotallowedtousethisgiftcard:'لا يسمح لك باستخدام بطاقة الهدايا هذه',
            tousethisdiscountcodeyoumustfirstlogin:'لاستخدام رمز الخصم هذا ، عليك تسجيل الدخول أولاً',
            pleasebepatient:'يرجى التحلي بالصبر',
            transferringtothebankportal:'التحويل إلى بوابة البنك',
            freedelivery:'توصيل مجاني',
            perudoor:'باب بيرو',
        },
        cartSuccess:{
            title:'عملية ناجحة',
            description:'تم تسجيل طلبك بنجاح ، انظر التفاصيل والفاتورة في الجدول أدناه'
        },
        cartFaild:{
            title:'عملية فاشلة',
            description:'واجهت عملية الشراء خطأ ، حاول مرة أخرى'
        },
        sex:{
            women:'النساء',
            men:'الرجال',
            boy:'بنات',
            girl:'بنین',
            children:'الأطفال',
            unisexadult:'بغض النظر عن جنس البالغين',
            unisexchild:'بغض النظر عن جنس الأطفال'
        },
        comment:{
            send:'إرسال تعليق',
            sendtextname1:'سيتم تسجيل تعليقك تحت اسم "',
            sendtextname2:'"',
            textarea:'اكتب تعليقك',
            sendsuccess:'سيتم عرض تعليقك بعد موافقة الإدارة',
            untitled:"بدون عنوان",
            dizasanswer:"إجابة ديزا",
        },
        dashboard:{
            title:'داشبورد',
            wellcome:'اهلا',
            profile:'الملف الشخصي',
            wishlist:'قائمة الرغبات',
            myorders:'طلباتي',
            mygifts:'الهدايا بلدي',
            referralrequest:'طلب الإحالة',
            notifications:'إشعارات',
            criticsandsuggestions:'النقاد والاقتراحات',
            recentvisits:'الزيارات الأخيرة',
            logout:'تسجيل خروج',
            imsureofleaving:"أنا متأكد من المغادرة",
            cancel:'يلغي',
            personalinformation:'معلومات شخصية',
            editinformation:'تحرير المعلومات',
            acceptandeditinformation:'قبول المعلومات وتحريرها',
            email:'البريد الإلكتروني',
            postaladdress:'العنوان البريدي',
            postalcode:'الرمز البريدي',
            country:'البلد',
            state:'الدولة',
            city:'المدينة',
            address:'عنوان',
            settings:'إعدادات',
            emptynotice:'قائمة الإخطار الخاصة بك فارغة',
            noticetype:'نوع إعلام',
            inventory:'جرد',
            discount:'خصم سلعة',
            productname:'اسم المنتج',
            brandname:'اسم العلامة التجارية',
            active:'نشيط',
            inactive:'غير نشط',
            mygifts:'الهدايا بلدي',
            mygiftsempty:'قائمة الهدايا الخاصة بك فارغة',
            giftdetails:'تفاصيل الهدية',
            finalamount:'القيمة النهائية',
            orderdate:'تاريخ الطلب',
            referralcode:'شفرة التتبع',
            amount:'سعر',
            count:'رقم',
            product:'المنتج',
            customized:'حسب الطلب',
            link:'حلقة الوصل',
            couponcode:'رمز التخفيض',
            physical:'بدني',
            digital:'رقمي',
            gifttype:'نوع الهدية',
            repayment:'السداد',
            successful:'دفع ناجح',
            faild:'هزم',
            downloadinvoice:'تحميل فاتورة',
            myordersempty:'قائمة الطلبات الخاصة بك فارغة',
            orderdetails:'تفاصيل الطلب',
            payathome:'الدفع الفوري',
            returnedpayathome:'دفع في الموقع (مرتجع)',
            grievance:{
                title:'طلب الإحالة',
                empty:'لحسن الحظ ، لم تقم بإرجاع منتج بعد',
                status:'حالة',
                eventdate:'تاريخ التسجيل',
                notapproved:'غير مقبول',
                approved:'تم تأكيد',
                pending:'قيد الانتظار',
                referralhistory:'تاریخچه ارجاع کالا',
                description:'وصف',
                order:'ترتيب',
                ordercode:'رمز الطلب',
                orderamount:'كمية الطلب',
                requestforreferral:'طلب إحالة البضائع',
                reasons:'يرجى كتابة أسبابك لنا',
                error:'تحتاج إلى تسجيل مخصص أولا',
                success:'تم تقديم طلبك بنجاح ، شكرا لك',
                submit:'تقديم طلب',
            },
            suggestions:{
                comment:'عزيزي المستخدم ، يمكنك إرسال تعليقاتك إلينا من أجل تقديم خدمة أفضل',
                submit:'إرسال تعليق',
                placeholder:'أكتب هنا',
                error:'لطفا پیام خود را درست وارد کنید',
                success:'تم تقديم تعليقك بنجاح ، شكرا لك',
            }
        },
        joinus:{
            title:'اعمل معنا',
            h1:'التعاون مع ديزا',
            description:'تسعى مجموعتنا جاهدة لتكون جسرا بين القيم وفن التصميم مع الجمهور. \nلتقديم وبيع المنتجات التي تم إنشاؤها من قبل المصممين الفنانين مع الإبداع والجودة بما يتماشى مع قيم الموضة المستدامة. يرجى ملء النموذج ذي الصلة لمزيد من المعلومات.',
            collaborationform:'شكل التعاون',
            designername:'اسم المصمم',
            brandname:'اسم العلامة التجارية',
            mobilenumber:'رقم الهاتف المحمول',
            email:'البريد الإلكتروني',
            experience:'خبرة',
            underoneyear:'أقل من عام',
            onetotwoyears:'من سنة إلى سنتين',
            twotofiveyears:'من سنتين إلى خمس سنوات',
            morethanfiveyears:'أكثر من خمس سنوات',
            workplace:'مكان العمل',
            instagrampageaddress:'صفحة Instagram',
            websiteaddress:'عنوان موقع ويب',
            whichcategory:'في أي فئة تقع منتجاتك؟',
            clothing:'ملابس',
            accessory:'ملحق',
            bag:'حقيبة',
            shoes:'حذاء',
            textarea:'يرجى كتابة وصف موجز عن علامتك التجارية',
            success:'تم تقديم طلبك بنجاح ، يرجى انتظار مكالمتنا',
            send:'تقديم طلب',
        },
        trustbox:["المنتجات ذات الأصالة","فن المصممين الإيرانيين","الدعم على مدار 24 ساعة","الإرسال السريع"],
        contactcomment:'عزيزي المستخدم ، يمكنك مشاركة تعليقاتك واقتراحاتك معنا من خلال ملء النموذج أدناه',
        contactsuccess:'تم تسجيل رسالتك بنجاح ، شكرا لك',
        loginwithmobile:'تسجيل الدخول عن طريق الهاتف المحمول',
        securitycode:'رمز الحماية',
        _securitycode:'رمز الحماية (أربعة أرقام)',
        logincomment:'إذا لم تكن قد سجلت بعد ، فسيتم تسجيل دخولك كمستخدم جديد',
        loginsms1:'تم إرسال رمز الحماية إلى ',
        loginsms2:'',
        resendsecuritycode:'إعادة إرسال رمز الحماية',
        changemobilenumber:'تغيير رقم الجوال',
        moreseconds:'ثوان أخرى',
        firstnameandlastname:'الاسم الأول واسم العائلة',
        mobilenumber:'رقم الهاتف المحمول',
        phonenumber:'رقم الهاتف',
        writeyourmessage:'اكتب رسالتك',
        email:'البريد الإلكتروني',
        sendmessage:'إرسال رسالة',
        captchahasexpired:'انتهت صلاحية كلمة التحقق',
        pleasemarkthecaptcha:'يرجى وضع علامة التحقق',
        pleaseenterallitems:'الرجاء إدخال كافة العناصر',
        loading:'يعالج',
        processing:'يتم المعالجة',
        result:'نتيجة',
        noproductsfound:'لا توجد منتجات',
        unavailable:'غير متوفره',
        gender:'جنس',
        onlydiscountproducts:'فقط المنتجات المخفضة',
        pricerange:'نطاق السعر',
        userarea:'منطقة المستخدم',
        loginsignup:'دخول / التسجيل',
        notifymewhenavailable:'يخطر لي عندما تكون متاحة',
        noticeofproductdiscounts:'إشعار بخصومات المنتج',
        favorites:'المفضلة',
        search:'بحث منتوج',
        dosearch:'یبحث',
        special:'ممیز',
        home:'الصفحة الرئيسية',
        designers:'المصممين',
        about:'عن',
        aboutdiza:'حـول دیــزا',
        products:'منتجات',
        giftcard:'كرت هدية',
        gift:{
            thegiftcarddoesnotbelongtoyou:'بطاقة الهدايا ليست ملكك.',
            todisplaythecodeyoumustfirstauthenticate:'لعرض الرمز ، يجب عليك المصادقة أولاً.',
            digitalversion:'نسخة رقمية',
            physicalversion:'النسخة المادية',
            digitalversioncomment:'يمكنك إرسال هذا الإصدار كارتباط للشخص الذي تريده',
            physicalversioncomment:'هذا الإصدار مطبوع بجودة عالية وسيتم إرساله إلى عنوان المرسل أو المستلم الذي تختاره',
            buygiftcard:'شراء بطاقة هدية',
            selecttheversionyouwant:'حدد الإصدار الذي تريده',
            choiceoccasion:'اختيار المناسبة',
            specifications:'تحديد',
            thepayment:'الدفع',
            completecontentofthecard:'أكمل محتوى البطاقة',
            writeyourmessage:'اكتب رسالتك (بحد أقصى 40 كلمة)',
            theamountpayable:'المبلغ المستحق',
            shippingtime:'وقت الشحن',
            address:'عنوان',
            mobilenumber:'رقم الهاتف المحمول',
            cardtype:'نوع البطاقة',
            recipientsname:'اسم المستقبل',
            cardamount:'مبلغ البطاقة',
            printed:'مطبوعة',
            digital:'رقمي',
            orderspecifications:'مواصفات الطلب',
            attentioncomment:'بعد الشراء ، يجب على المستلم إدخال رقمه للتأكيد ومشكلات الأمان ، لذا تأكد من إدخاله بشكل صحيح',
            attention:'انتباه',
            firstnameandlastname:'الاسم الأول واسم العائلة',
            receiverspecifications:'مواصفات جهاز الاستقبال',
            completeaddress:'العنوان الكامل',
            iammyownreceiver:'أنا جهاز الاستقبال الخاص بي',
        },
        notify:{
            coupontext:'سيتم إخطارك بالخصومات الحصرية على هذا المنتج إلى رقم هاتفك المحمول',
            inventorytext:'في حالة إعادة الجرد سيتم إعلامك برقم جوالك',
        },
        realized:'أدركت',
        completeyourstyle:'أكمل أسلوبك',
        howtocare:'كيف نهتم',
        productdescription:'وصف المنتج',
        productdetails:'تفاصيل المنتج',
        unavailablecomment:'هذا المنتج غير متوفر حاليا',
        productsizes:'أحجام المنتج',
        size:'مقاس',
        sizespecifications:'مواصفات الحجم',
        othercolors:'الوان اخرى',
        sewingorder:'ترتيب الخياطة',
        custommade:'مصنوع بطريقة مخصصة',
        notavailable:'هذا المنتج غير متوفر',
        addtocart:'أضف إلى السلة',
        letmeknow:'دعني اعرف',
        producseo1:'تسوق اونلاين ',
        producseo2:' صممه ',
        producseo3:'',
        designer:'مصمم',
        brand:'ماركة',
        transferringtothebank:'التحويل إلى بوابة البنك',
        faildpurchase:'عملية شراء غير ناجحة',
        successpurchasetext1:'تم الشراء بنجاح وسيتم إرساله إليك في',
        successpurchasetext2:'',
        successpurchasetext3:'تمت عملية الشراء بنجاح ، يمكنك الآن إرسال رابط بطاقة الهدايا إلى الشخص.',
        successpurchase:'عملية شراء ناجحة',
        backtomainpage:'ارجع للصفحة الرئيسية',
        previousstep:'خطوة سابقة',
        nextstep:'خطوة التالية',
        receivingdata:'جار استقبال البيانات',
        copylink:'انسخ الرابط',
        copycode:'رمز النسخ',
        other:'آخر',
        all:'الجميع',
        searchfor:'ابحث عن',
        orderby:'ترتيب حسب',
        sortByHit:'أكثر زيارة',
        sortByNewest:'الاجدد',
        sortByValuable:'أعلى سعر',
        sortByCutrate:'أقل سعر',
        latest:'أحدث',
        expensive:'أغلى',
        economical:'أرخص',
        popular:'أشهر',
        filter:'منقي',
        filterby:'مصنف بواسطة',
        applyfilters:'تطبيق المرشحات',
        applypricefilter:'تطبيق مرشح السعر',
        from:'من',
        upto:'ما يصل إلى',
        minutesstudy:'دقائق دراسة',
        visits:'زيارة',
        video:'فيديو',
        article:'مقال',
        podcast:'بودكاست',
        discounted:'مخفضة',
        seemore:'شاهد المزيد',
        dizadesigners:'مصممي الدیــزا',
        joindiza:'انضم إلدیزا',
        categories:'التجمع',
        _categories:'التجمع',
        guest:'ضيف',
        recentvisits:'الزيارات الأخيرة',
        similarproducts:'منتجات مماثلة',
        more:'أكثر',
        fewer:'أقل',
        back:'العودة',
        backtotop:'عد إلى الأعلى',
    }
}